version: '3.3'
services:

  app:
    container_name: marvel_app
    build: .
    volumes:
        - ./api:/var/www
        - ./config/startups/config.sh:/opt/config.sh
        - ./config/app.env:/var/www/.env
    command: bash -c "bash /opt/config.sh && tail -f /dev/null"
    networks:
      - app-network

  mysql:
    container_name: marvel_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: marvel
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: marvel
      MYSQL_DATABASE: marvel
    volumes:
      - ./db_mysql:/var/lib/mysql
      - ./config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
    - "3307:3306"
    networks:
      - app-network

  nginx:
    container_name: marvel_nginx
    image: nginx
    volumes:
      - ./api:/var/www
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local